### ISSUE TITLE
Add Polars to stack

### ISSUE THREAD

**Issue by MarcoGorelli** [panstacks/pandata#3]
May I suggest that you add Polars to the stack?

It can help solve real problems for real people (e.g. https://www.confessionsofadataguy.com/polars-vs-pandas-inside-an-aws-lambda/), and like the rest of the tools, is also free and open source 

You already have multiple tools which do similar things in the visualisation part, so I'd suggest having an extra (powerful) tool in the "data API" part

Furthermore, note that the visualisation tools noted typically do support Polars by leveraging the DataFrame Interchange Protocol

**Comment by jbednar** [comment]
Now that Polars is well supported by hvPlot, it should definitely be added to the stack.
